""" generate random tests to test backend and visualisation tools """

import random
from libs.backend.dsa_game import GameLogic, GameState
from libs.languages.languages import english
from libs.backend.dsa_data import Attribute, Skill, Spell, FightTalent

if __name__ == '__main__':
    configs = {"output file": "output.csv",
               "interface": "CLI",
               "dice": "auto",
               "hero folder": "hero_files",
               "language": "english",
               "font size": 14,
               "width": 200,
               "height": 200,
               "scaling": 1}
    lang = english
    game = GameLogic(configs, lang)
    state = GameState()
    state.dice = "auto"

    for i in range(200):

        state.current_hero = list(game.heroes)[random.randint(0, len(game.heroes)-1)]

        hero = game.heroes[state.current_hero]

        entry_list = hero.attrs[0:8] + hero.skills + hero.spells + hero.fight_talents

        random_test = entry_list[random.randint(0, len(entry_list)-1)]
        if isinstance(random_test, Attribute):
            state.category = "attr"
        elif isinstance(random_test, Skill):
            state.category = "skill"
        elif isinstance(random_test, Spell):
            state.category = "spell"
        elif isinstance(random_test, FightTalent):
            state.category = "fight_talent"
        state.name = random_test.name

        state.mod = random.randint(-5, 5)

        state = game.test(state)

        state.desc = "generated by test_generator.py"

        state = game.save_to_csv(state)
