""" generate random tests to test backend and visualisation tools """

import random

from libs.backend.dsa_game import GameLogic, GameState
from libs.languages.languages import english

if __name__ == '__main__':
    configs = {"output file": "../../output.csv",
               "interface": "CLI",
               "dice": "auto",
               "hero folder": "../../hero_files",
               "language": "english",
               "font size": 14,
               "width": 200,
               "height": 200,
               "scaling": 1}
    lang = english
    game = GameLogic(configs, lang)
    state = GameState()
    state.dice = "auto"

    for i in range(200):

        state.current_hero = list(game._heroes)[random.randint(0, len(game._heroes) - 1)]

        hero = game._heroes[state.current_hero]

        entry_list = hero.attrs[0:8]
        entry_list += hero.skills
        entry_list += hero.spells
        entry_list += hero.fight_talents
        entry_list += hero.advantages

        state.selection = entry_list[random.randint(0, len(entry_list) - 1)]

        state.mod = random.randint(-5, 5)

        state = game.test(state)

        state.desc = "generated by test_generator.py"

        state = game.save_to_csv(state)
